module.exports = {
	MONGO_DB: process.env.MONGO_DB,
	JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
	MAILGUN_API_KEY: process.env.MAILGUN_API_KEY,
	MAILGUN_DOMAIN: process.env.MAILGUN_DOMAIN,
	MAILGUN_PUBLIC_KEY: process.env.MAILGUN_PUBLIC_KEY,
	MAILGUN_SMTP_LOGIN: process.env.MAILGUN_SMTP_LOGIN,
	MAILGUN_SMTP_PASSWORD: process.env.MAILGUN_SMTP_PASSWORD,
	MAILGUN_SMTP_PORT: process.env.MAILGUN_SMTP_PORT,
	MAILGUN_SMTP_SERVER: process.env.MAILGUN_SMTP_SERVER,
};

